# fly.toml app configuration file generated for dry-sky-3369 on 2023-05-17T16:28:00+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "dry-sky-3369"
primary_region = "lhr"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
